/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/apoorvajagtap/trackPodCRD/pkg/apis/trackpod/v1"
	trackpodv1 "github.com/apoorvajagtap/trackPodCRD/pkg/client/applyconfiguration/trackpod/v1"
	scheme "github.com/apoorvajagtap/trackPodCRD/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TrackPodsGetter has a method to return a TrackPodInterface.
// A group's client should implement this interface.
type TrackPodsGetter interface {
	TrackPods(namespace string) TrackPodInterface
}

// TrackPodInterface has methods to work with TrackPod resources.
type TrackPodInterface interface {
	Create(ctx context.Context, trackPod *v1.TrackPod, opts metav1.CreateOptions) (*v1.TrackPod, error)
	Update(ctx context.Context, trackPod *v1.TrackPod, opts metav1.UpdateOptions) (*v1.TrackPod, error)
	UpdateStatus(ctx context.Context, trackPod *v1.TrackPod, opts metav1.UpdateOptions) (*v1.TrackPod, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.TrackPod, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.TrackPodList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.TrackPod, err error)
	Apply(ctx context.Context, trackPod *trackpodv1.TrackPodApplyConfiguration, opts metav1.ApplyOptions) (result *v1.TrackPod, err error)
	ApplyStatus(ctx context.Context, trackPod *trackpodv1.TrackPodApplyConfiguration, opts metav1.ApplyOptions) (result *v1.TrackPod, err error)
	TrackPodExpansion
}

// trackPods implements TrackPodInterface
type trackPods struct {
	client rest.Interface
	ns     string
}

// newTrackPods returns a TrackPods
func newTrackPods(c *AjV1Client, namespace string) *trackPods {
	return &trackPods{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the trackPod, and returns the corresponding trackPod object, and an error if there is any.
func (c *trackPods) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.TrackPod, err error) {
	result = &v1.TrackPod{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trackpods").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TrackPods that match those selectors.
func (c *trackPods) List(ctx context.Context, opts metav1.ListOptions) (result *v1.TrackPodList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.TrackPodList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("trackpods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested trackPods.
func (c *trackPods) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("trackpods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a trackPod and creates it.  Returns the server's representation of the trackPod, and an error, if there is any.
func (c *trackPods) Create(ctx context.Context, trackPod *v1.TrackPod, opts metav1.CreateOptions) (result *v1.TrackPod, err error) {
	result = &v1.TrackPod{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("trackpods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trackPod).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a trackPod and updates it. Returns the server's representation of the trackPod, and an error, if there is any.
func (c *trackPods) Update(ctx context.Context, trackPod *v1.TrackPod, opts metav1.UpdateOptions) (result *v1.TrackPod, err error) {
	result = &v1.TrackPod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trackpods").
		Name(trackPod.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trackPod).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *trackPods) UpdateStatus(ctx context.Context, trackPod *v1.TrackPod, opts metav1.UpdateOptions) (result *v1.TrackPod, err error) {
	result = &v1.TrackPod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("trackpods").
		Name(trackPod.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(trackPod).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the trackPod and deletes it. Returns an error if one occurs.
func (c *trackPods) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trackpods").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *trackPods) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("trackpods").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched trackPod.
func (c *trackPods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.TrackPod, err error) {
	result = &v1.TrackPod{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("trackpods").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied trackPod.
func (c *trackPods) Apply(ctx context.Context, trackPod *trackpodv1.TrackPodApplyConfiguration, opts metav1.ApplyOptions) (result *v1.TrackPod, err error) {
	if trackPod == nil {
		return nil, fmt.Errorf("trackPod provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(trackPod)
	if err != nil {
		return nil, err
	}
	name := trackPod.Name
	if name == nil {
		return nil, fmt.Errorf("trackPod.Name must be provided to Apply")
	}
	result = &v1.TrackPod{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("trackpods").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *trackPods) ApplyStatus(ctx context.Context, trackPod *trackpodv1.TrackPodApplyConfiguration, opts metav1.ApplyOptions) (result *v1.TrackPod, err error) {
	if trackPod == nil {
		return nil, fmt.Errorf("trackPod provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(trackPod)
	if err != nil {
		return nil, err
	}

	name := trackPod.Name
	if name == nil {
		return nil, fmt.Errorf("trackPod.Name must be provided to Apply")
	}

	result = &v1.TrackPod{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("trackpods").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
