/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/apoorvajagtap/trackPodCRD/pkg/apis/trackpod/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrackPods implements TrackPodInterface
type FakeTrackPods struct {
	Fake *FakeAjV1
	ns   string
}

var trackpodsResource = v1.SchemeGroupVersion.WithResource("trackpods")

var trackpodsKind = v1.SchemeGroupVersion.WithKind("TrackPod")

// Get takes name of the trackPod, and returns the corresponding trackPod object, and an error if there is any.
func (c *FakeTrackPods) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.TrackPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trackpodsResource, c.ns, name), &v1.TrackPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrackPod), err
}

// List takes label and field selectors, and returns the list of TrackPods that match those selectors.
func (c *FakeTrackPods) List(ctx context.Context, opts metav1.ListOptions) (result *v1.TrackPodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trackpodsResource, trackpodsKind, c.ns, opts), &v1.TrackPodList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.TrackPodList{ListMeta: obj.(*v1.TrackPodList).ListMeta}
	for _, item := range obj.(*v1.TrackPodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trackPods.
func (c *FakeTrackPods) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trackpodsResource, c.ns, opts))

}

// Create takes the representation of a trackPod and creates it.  Returns the server's representation of the trackPod, and an error, if there is any.
func (c *FakeTrackPods) Create(ctx context.Context, trackPod *v1.TrackPod, opts metav1.CreateOptions) (result *v1.TrackPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trackpodsResource, c.ns, trackPod), &v1.TrackPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrackPod), err
}

// Update takes the representation of a trackPod and updates it. Returns the server's representation of the trackPod, and an error, if there is any.
func (c *FakeTrackPods) Update(ctx context.Context, trackPod *v1.TrackPod, opts metav1.UpdateOptions) (result *v1.TrackPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trackpodsResource, c.ns, trackPod), &v1.TrackPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrackPod), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTrackPods) UpdateStatus(ctx context.Context, trackPod *v1.TrackPod, opts metav1.UpdateOptions) (*v1.TrackPod, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(trackpodsResource, "status", c.ns, trackPod), &v1.TrackPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrackPod), err
}

// Delete takes name of the trackPod and deletes it. Returns an error if one occurs.
func (c *FakeTrackPods) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(trackpodsResource, c.ns, name, opts), &v1.TrackPod{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrackPods) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trackpodsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.TrackPodList{})
	return err
}

// Patch applies the patch and returns the patched trackPod.
func (c *FakeTrackPods) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.TrackPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trackpodsResource, c.ns, name, pt, data, subresources...), &v1.TrackPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.TrackPod), err
}
