---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trackpods.aj.com
spec:
  group: aj.com
  names:
    kind: TrackPod
    listKind: TrackPodList
    plural: trackpods
    singular: trackpod
    shortNames:
    - tpod
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                message:
                  type: string
                count:
                  type: integer
            status:
              type: object
              properties:
                progress:
                  type: string
                count:
                  type: integer
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []